# This is a basic workflow to help you get started with Actions

name: Environments

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - '**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
##################
  # Set Deploy Env #
  ##################
    SetDeployEnv:
      name: 'Set Deployment Environment'
      runs-on: ubuntu-latest
      outputs:
        deploy_env: ${{ steps.get_env.outputs.deploy_env }}
        
      steps:
      - name: Determine Environment
        id: get_env
        run: |
            if [[ ${{ github.ref }} 'refs/heads/main'; then
                echo "::set-output name=deploy_env::Production"
            else
                echo "::set-output name=deploy_env::Development"
            fi
  
  ################
    # Test Job     #
    ################
    TestJob:
      needs: SetDeployEnv
      name: 'Deployment to Environment'
      runs-on: ubuntu-latest
      environment: 
          name: ${{ needs.SetDeployEnv.outputs.deploy_env }}
  
      steps:
        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            echo Secret value is : ${{ secrets.MY_SECRET }}
            echo Variable value is : ${{ vars.MY_VAR }}
